name: Push to live_webpage

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Push changes to live_webpage
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git checkout -b live_webpage
        git merge origin/master
        git add .
        git commit -m "Automatic update from master"
        git push origin live_webpage
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }} # Use PAT_TOKEN secret for authentication
